#!/usr/bin/env python3
"""Generates the codebooks and test fixtures that tie the Swift library to its specification.

    python3 gen_fixtures.py codebooks   # codebooks.json and Sources/PITCH/TurboCodebooks.swift
    python3 gen_fixtures.py parity      # Tests/PITCHTests/Fixtures/parity.json          (ParityTests)
    python3 gen_fixtures.py channel     # Tests/PITCHTests/Fixtures/channel_parity.json  (PerChannelTests)
    python3 gen_fixtures.py all         # all three
"""
import argparse, base64, json, sys, time
from pathlib import Path
import numpy as np
import pitch_reference as R

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SWIFT_CODEBOOKS = ROOT / "Sources" / "PITCH" / "TurboCodebooks.swift"
PARITY_OUT = ROOT / "Tests" / "PITCHTests" / "Fixtures" / "parity.json"
CHANNEL_OUT = ROOT / "Tests" / "PITCHTests" / "Fixtures" / "channel_parity.json"


def f32(a): return base64.b64encode(np.asarray(a, dtype="<f4").tobytes()).decode()
def u16(a): return base64.b64encode(np.asarray(a, dtype="<f2").view("<u2").tobytes()).decode()


# ----------------------------------------------------------------------------- codebooks
def codebooks(args):
    t0 = time.time()
    books = {}
    for d in R.SUPPORTED_DIMS:
        for b in R.SUPPORTED_BITS:
            books[(d, b)] = R.compute_sphere_codebook(d, b).astype(np.float32)
        print(f"  d={d:4d} done ({time.time() - t0:.0f}s)", file=sys.stderr)

    (HERE / "codebooks.json").write_text(json.dumps(
        {f"{d}_{b}": [float(v) for v in cb] for (d, b), cb in books.items()}))

    lines = [
        "// TurboCodebooks.swift",
        "// GENERATED by reference/gen_fixtures.py codebooks. Do not edit by hand.",
        "//",
        "// Lloyd-Max codebooks for one coordinate of a uniformly random unit vector in R^d",
        "// (density proportional to (1 - x^2)^((d-3)/2)), the distribution TurboQuant's",
        "// analysis assumes after rotation. Indexed by (dim, bits); values are float32 and",
        "// sorted ascending, which the kernel's binary search relies on.",
        "",
        "enum TurboCodebooks {",
        "    static func codebook(dim: Int, bits: Int) -> [Float]? {",
        "        switch (dim, bits) {",
    ]
    for (d, b) in books:
        lines.append(f"        case ({d}, {b}): return d{d}b{b}")
    lines += ["        default: return nil", "        }", "    }", ""]
    for (d, b), cb in books.items():
        vals = ", ".join(repr(float(np.float32(v))) for v in cb)
        lines.append(f"    private static let d{d}b{b}: [Float] = [{vals}]")
    lines.append("}")
    SWIFT_CODEBOOKS.parent.mkdir(parents=True, exist_ok=True)
    SWIFT_CODEBOOKS.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(books)} codebooks to codebooks.json and {SWIFT_CODEBOOKS}", file=sys.stderr)


# ----------------------------------------------------------------------------- per-vector parity fixture
def parity(args):
    rng = np.random.default_rng(2026)
    groups = {}
    if args.kv.exists():
        vecs = json.loads(args.kv.read_text())["vectors"]
        keys = [v["data"] for v in vecs if v["type"] == "key"][:16]
        vals = [v["data"] for v in vecs if v["type"] == "value"][:16]
        groups["kv64"] = np.array(keys + vals, dtype=np.float32)
        kv_source = str(args.kv.name)
    else:  # Gaussian with a few outlier channels, so the fixture never depends on the data files
        g = rng.standard_normal((32, 64)); g[:, :4] *= 8
        groups["kv64"] = g.astype(np.float32)
        kv_source = "synthetic (kv file not found)"
    groups["gauss2"] = rng.standard_normal((8, 2)).astype(np.float32)
    groups["gauss16"] = rng.standard_normal((8, 16)).astype(np.float32)
    groups["gauss256"] = rng.standard_normal((8, 256)).astype(np.float32)
    groups["gauss1024"] = rng.standard_normal((2, 1024)).astype(np.float32)

    cases = []
    for gname, X32 in groups.items():
        X = X32.astype(np.float64)                  # the kernel sees exactly these float32 values
        for method in ("turboQuant", "polarQuant"):
            for bits in (2, 3, 4, 8):
                seed = 12345 if (gname == "gauss16" and bits == 4) else R.DEFAULT_SEED
                codes, scales = R.ENCODERS[method](X, bits, seed)
                scales32 = np.asarray(scales, dtype=np.float32)
                recon = R.DECODERS[method](codes, scales32.astype(np.float64), bits, seed)
                rel = float((((X - recon) ** 2).sum(1) / (X ** 2).sum(1)).mean())
                cases.append(dict(group=gname, method=method, bits=bits, seed=seed,
                                  codes=base64.b64encode(R.pack_codes(codes, bits)).decode(),
                                  scales=f32(scales32), reconstruction=f32(recon),
                                  relative_error=rel))

    PARITY_OUT.parent.mkdir(parents=True, exist_ok=True)
    PARITY_OUT.write_text(json.dumps(dict(
        generator="reference/gen_fixtures.py parity", kv_source=kv_source,
        groups=[dict(name=n, dim=int(X.shape[1]), count=int(X.shape[0]), input=f32(X)) for n, X in groups.items()],
        cases=cases), indent=1))
    print(f"wrote {len(cases)} cases over {len(groups)} groups to {PARITY_OUT} ({PARITY_OUT.stat().st_size // 1024} KB)")


# ----------------------------------------------------------------------------- per-channel parity fixture
def _offset_keys(rng, n, d):
    """Gaussian keys plus large near-constant offsets on a few channels, like Qwen's key bias."""
    X = rng.standard_normal((n, d))
    X[:, :4] += np.array([40.0, -25.0, 18.0, -12.0]) + 0.3 * rng.standard_normal((n, 4))
    return X.astype(np.float32)


def _channel_case(gname, X, bits, G):
    codes, ranges = R.channel_encode(X, bits, G)
    recon = R.channel_decode(codes, ranges, bits, G)
    mse = float(((X.astype(np.float64) - recon) ** 2).mean())
    return dict(group=gname, bits=bits, group_size=G,
                codes=base64.b64encode(R.pack_codes(codes, bits)).decode(),
                ranges=u16(ranges), reconstruction=f32(recon), mse=mse)


def channel(args):
    rng = np.random.default_rng(2026)
    groups = {}
    if args.blocks.exists():
        data = json.loads(args.blocks.read_text())
        blk, d = data["blocks"][0], data["dim"]
        K = np.frombuffer(base64.b64decode(blk["keys"]), dtype="<f4").reshape(blk["seq_len"], d)
        groups["qwen_keys"] = K[:150].copy()
        source = f"{args.blocks.name}, block 0 (layer {blk['layer']}, kv head {blk['kv_head']})"
    else:
        groups["qwen_keys"] = _offset_keys(rng, 150, 64)
        source = "synthetic (attention block file not found)"
    groups["offset64"] = _offset_keys(rng, 150, 64)
    groups["offset96"] = _offset_keys(rng, 100, 96)          # not a power of two
    groups["gauss128"] = rng.standard_normal((130, 128)).astype(np.float32)

    cases = []
    for gname, X in groups.items():
        for bits in (2, 3, 4, 8):
            cases.append(_channel_case(gname, X, bits, R.CHANNEL_DEFAULT_GROUP))
    cases.append(_channel_case("offset64", groups["offset64"], 4, 16))

    CHANNEL_OUT.parent.mkdir(parents=True, exist_ok=True)
    CHANNEL_OUT.write_text(json.dumps(dict(
        generator="reference/gen_fixtures.py channel", source=source,
        groups=[dict(name=n, dim=int(X.shape[1]), count=int(X.shape[0]), input=f32(X)) for n, X in groups.items()],
        cases=cases), indent=1))
    print(f"wrote {len(cases)} cases over {len(groups)} groups to {CHANNEL_OUT} ({CHANNEL_OUT.stat().st_size // 1024} KB)")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("what", choices=["codebooks", "parity", "channel", "all"])
    ap.add_argument("--kv", type=Path, default=HERE / "kv_vectors_qwen.json", help="KV vectors for the parity fixture")
    ap.add_argument("--blocks", type=Path, default=HERE / "attn_blocks_qwen.json", help="attention blocks for the channel fixture")
    args = ap.parse_args()
    for step in (["codebooks", "parity", "channel"] if args.what == "all" else [args.what]):
        {"codebooks": codebooks, "parity": parity, "channel": channel}[step](args)


if __name__ == "__main__":
    main()
