#!/usr/bin/env python3
import json, sys, time
from pathlib import Path
import numpy as np
from pitch_reference import compute_sphere_codebook, SUPPORTED_DIMS, SUPPORTED_BITS

HERE = Path(__file__).resolve().parent
SWIFT_OUT = HERE.parent / "Sources" / "PITCH" / "TurboCodebooks.swift"

def main():
    t0 = time.time()
    books = {}
    for d in SUPPORTED_DIMS:
        for b in SUPPORTED_BITS:
            books[(d, b)] = compute_sphere_codebook(d, b).astype(np.float32)
        print(f"  d={d:4d} done ({time.time() - t0:.0f}s)", file=sys.stderr)

    (HERE / "codebooks.json").write_text(json.dumps(
        {f"{d}_{b}": [float(v) for v in cb] for (d, b), cb in books.items()}))

    lines = [
        "// TurboCodebooks.swift",
        "// GENERATED by reference/gen_codebooks.py. Do not edit by hand.",
        "//",
        "// Lloyd-Max codebooks for one coordinate of a uniformly random unit vector in R^d",
        "// (density proportional to (1 - x^2)^((d-3)/2)), the distribution TurboQuant's",
        "// analysis assumes after rotation. Indexed by (dim, bits); values are float32 and",
        "// sorted ascending, which the kernel's binary search relies on.",
        "",
        "enum TurboCodebooks {",
        "    static func codebook(dim: Int, bits: Int) -> [Float]? {",
        "        switch (dim, bits) {",
    ]
    for (d, b) in books:
        lines.append(f"        case ({d}, {b}): return d{d}b{b}")
    lines += ["        default: return nil", "        }", "    }", ""]
    for (d, b), cb in books.items():
        vals = ", ".join(repr(float(np.float32(v))) for v in cb)
        lines.append(f"    private static let d{d}b{b}: [Float] = [{vals}]")
    lines.append("}")
    SWIFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    SWIFT_OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(books)} codebooks to codebooks.json and {SWIFT_OUT}", file=sys.stderr)

if __name__ == "__main__":
    main()
